// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteFirstRun(arg1) {
  return window['go']['main']['App']['CompleteFirstRun'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResizeNow() {
  return window['go']['main']['App']['ResizeNow']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetActivePreset(arg1) {
  return window['go']['main']['App']['SetActivePreset'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetCenterAfterResize(arg1) {
  return window['go']['main']['App']['SetCenterAfterResize'](arg1);
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}
