// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CompleteFirstRun(arg1:boolean):Promise<main.Config>;

export function GetSettings():Promise<main.Config>;

export function GetVersion():Promise<string>;

export function Quit():Promise<void>;

export function ResizeNow():Promise<void>;

export function SaveSettings(arg1:main.Config):Promise<main.Config>;

export function SaveSettingsIfUnchanged(arg1:main.Config,arg2:main.Config):Promise<main.Config>;

export function SetActivePreset(arg1:string):Promise<main.Config>;

export function SetAutoStart(arg1:boolean):Promise<main.Config>;

export function SetCenterAfterResize(arg1:boolean):Promise<main.Config>;

export function ShowAbout():Promise<void>;

export function ShowSettings():Promise<void>;
